from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken.views import obtain_auth_token
from accounts.views import RegisterView
from .deployment_views import health, open_app

from projects.views import (
    AttachmentDownloadView,
    AttachmentListCreateView,
    ProjectListCreateView,
    ProjectDetailView,
    ProjectActivityView,
    NotificationListView,
    NotificationSyncView,
    NotificationDetailView,
    NotificationReadAllView,
    ProjectSlotView,
    ProjectSlotDetailView,
    InvitationView,
    InvitationJoinView,
    AssignmentCandidatesView,
    TaskAssignmentView,
    TaskEditorsView,
    TaskAssignmentProgressView,
    MilestoneListCreateView,
    MilestoneDetailView,
    IdeaListCreateView,
    IdeaDetailView,
    IdeaConvertView,
    TaskCommentListCreateView,
    TaskCommentDetailView,
    IdeaCommentListCreateView,
    IdeaCommentDetailView,
    TaskDetailView,
    TaskListCreateView,
)

urlpatterns = [
    path("", open_app, name="open-app"),
    path("api/health/", health, name="api-health"),
    path("admin/", admin.site.urls),
    path("api/projects/", ProjectListCreateView.as_view(), name="project-list"),
    path("api/projects/<int:pk>/", ProjectDetailView.as_view(), name="project-detail"),
    path("api/projects/<int:project_id>/activity/", ProjectActivityView.as_view(), name="project-activity"),
    path("api/notifications/", NotificationListView.as_view(), name="notification-list"),
    path("api/notifications/sync/", NotificationSyncView.as_view(), name="notification-sync"),
    path("api/notifications/read-all/", NotificationReadAllView.as_view(), name="notification-read-all"),
    path("api/notifications/<int:pk>/", NotificationDetailView.as_view(), name="notification-detail"),
    path("api/register/", RegisterView.as_view(), name="api-register"),
    path("api/invitations/<str:code>/", InvitationView.as_view(), name="invitation-detail"),
    path("api/invitations/<str:code>/join/", InvitationJoinView.as_view(), name="invitation-join"),
    path("api/projects/<int:project_id>/slots/", ProjectSlotView.as_view(), name="project-slots"),
    path("api/projects/<int:project_id>/slots/<int:slot_id>/", ProjectSlotDetailView.as_view(), name="project-slot-detail"),
    path("api/projects/<int:project_id>/assignment-candidates/", AssignmentCandidatesView.as_view(), name="assignment-candidates"),
    path("api/projects/<int:project_id>/milestones/", MilestoneListCreateView.as_view(), name="milestone-list"),
    path("api/projects/<int:project_id>/milestones/<int:pk>/", MilestoneDetailView.as_view(), name="milestone-detail"),
    path("api/projects/<int:project_id>/ideas/", IdeaListCreateView.as_view(), name="idea-list"),
    path("api/projects/<int:project_id>/ideas/<int:pk>/", IdeaDetailView.as_view(), name="idea-detail"),
    path("api/projects/<int:project_id>/ideas/<int:idea_id>/convert/", IdeaConvertView.as_view(), name="idea-convert"),
    path("api/projects/<int:project_id>/ideas/<int:idea_id>/comments/", IdeaCommentListCreateView.as_view(), name="idea-comments"),
    path("api/projects/<int:project_id>/ideas/<int:idea_id>/comments/<int:pk>/", IdeaCommentDetailView.as_view(), name="idea-comment-detail"),
    path("api/projects/<int:project_id>/tasks/<int:task_id>/comments/", TaskCommentListCreateView.as_view(), name="task-comments"),
    path("api/projects/<int:project_id>/tasks/<int:task_id>/comments/<int:pk>/", TaskCommentDetailView.as_view(), name="task-comment-detail"),
    path("api/projects/<int:project_id>/tasks/<int:task_id>/assignments/", TaskAssignmentView.as_view(), name="task-assignments"),
    path("api/projects/<int:project_id>/tasks/<int:task_id>/editors/", TaskEditorsView.as_view(), name="task-editors"),
    path("api/projects/<int:project_id>/tasks/<int:task_id>/assignments/<int:user_id>/", TaskAssignmentProgressView.as_view(), name="task-assignment-progress"),
    path(
        "api/projects/<int:project_id>/tasks/",
        TaskListCreateView.as_view(),
        name="task-list",
    ),
    path(
        "api/projects/<int:project_id>/tasks/<int:pk>/",
        TaskDetailView.as_view(),
        name="task-detail",
    ),
    path(
        "api/projects/<int:project_id>/tasks/<int:task_id>/attachments/",
        AttachmentListCreateView.as_view(),
        name="attachment-list",
    ),
    path(
        "api/projects/<int:project_id>/tasks/<int:task_id>/attachments/"
        "<int:attachment_id>/download/",
        AttachmentDownloadView.as_view(),
        name="attachment-download",
    ),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    path("api/login/", obtain_auth_token, name="api-login"),
]
