# Generated by Django 6.1.1 on 2026-09-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='canvas_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
